image: amazon/aws-cli:latest

pipelines:
  default:
    - step:
        name: Deploy to S3
        caches:
          - docker
        script:
          - echo "Deploying static site to S3..."
          - aws s3 sync ./dist s3://www.mydigitalgate.io --delete
